spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Instagram
    username: root
    password: juanxiu14!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect  # MySQL Dialect 추가
    show-sql: true
    properties:
      hibernate:
        format_sql: true
